# frontend-chart/values.yaml
replicaCount: 1

image:
  repository: shrikantk7/frontendtest
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  name: http
  protocol: TCP
  targetPort: 80
  port: 80
  nodePort: 30001

serviceAccount:
  create: false

ingress:
  enabled: true
  host: calculator.com
  pathType: Prefix
  path: /frontend

autoscaling:
 enabled: false

resources: {}