# backend-chart/values.yaml
replicaCount: 1

image:
  repository: shrikantk7/backendtest
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  name: http
  protocol: TCP
  targetPort: 5000
  port: 5000

serviceAccount:
  create: false

ingress:
  enabled: true
  host: calculator.com
  pathType: Prefix
  path: /backend

autoscaling:
 enabled: false

resources: {}